# Generated by Django 6.0.3 on 2026-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(max_length=150),
        ),
    ]
