# Generated by Django 6.0.4 on 2026-04-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Shared', 'Shared')], max_length=20)),
                ('total_rooms', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='courses.course')),
            ],
            options={
                'ordering': ['hostel_name'],
            },
        ),
    ]
