# Generated by Django 6.0.3 on 2026-04-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_name_alter_course_specialization'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_facilities', to='courses.course'),
        ),
    ]
