# Generated by Django 6.0.4 on 2026-04-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('course_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=2)),
                ('duration', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
