# Generated by Django 6.0.3 on 2026-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='route_number',
            field=models.CharField(max_length=20),
        ),
    ]
